---
- name: Teste Semaphore
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Criar arquivo
      copy:
        content: "Testado!!"
        dest: /tmp/teste_semaphore.txt

    - name: Exibir mensagem
      debug:
        msg: "Arquivo criado com sucesso"
